version: '2'

services:
  web:
    image: gregsilcox/cashtrickle:1.0
    command: rails s -b '0.0.0.0'
    volumes:
      - .:/cashflow
      - bundler:/bundle
    ports:
      - "3003:3000"
    depends_on:
      - redis

  redis:
    image: redis

volumes:
  bundler:

# docker-compose build web
# docker-compose run web bundle install --path /bundle
# docker-compose run rails db:migrate
# docker-compose up
